NB. Each new term in the Fibonacci sequence
NB. is generated by adding the previous two
NB. terms. By starting with 1 and 2, the
NB. first 10 terms will be:

NB. 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

NB. By considering the terms in the Fibonacci
NB. sequence whose values do not exceed four
NB. million, find the sum of the even-valued
NB. terms.

fib=: 3 : 'y,+/_2 _1{y'
a=: fib^:(34) 0 1 NB. 34 by trial-and-error
s=: +/(0=2|a)#a
